### ISSUE TITLE
考虑一下原生支持apple silicon

### ISSUE THREAD

**Issue by LazingLuo** [lengain/BanbdAdForSafari#4]
考虑一下原生支持apple silicon？

**Comment by lengain** [comment]
只能等我换了电脑或者其他人提交代码了。。。。

**Comment by lengain** [comment]
> 考虑一下原生支持apple silicon？

只能等我换了电脑或者其他人提交代码了。。。。

**Comment by LazingLuo** [comment]
> > 考虑一下原生支持apple silicon？
> 
> 只能等我换了电脑或者其他人提交代码了。。。。

呃。。。那好像有点惨啊。
可惜我也不会折腾mac上的代码。

**Comment by R0uter** [comment]
不需要换电脑，Xcode 12.5 可以直接编译 Universal app 呀。

**Comment by lengain** [comment]
发布最新版了，重新安装一下，应该没啥问题了
